"""Added new tables

Revision ID: 04f43a991d45
Revises: 88c5ccd96324
Create Date: 2021-02-25 23:27:05.699639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04f43a991d45'
down_revision = '88c5ccd96324'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('adress', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('adress_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'adresses', ['adress_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'adress_id')
    op.drop_table('adresses')
    # ### end Alembic commands ###
