"""fixed tables

Revision ID: bd2340b01efd
Revises: 04f43a991d45
Create Date: 2021-02-26 00:00:48.901321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd2340b01efd'
down_revision = '04f43a991d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_adresses_id'), 'adresses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adresses_id'), table_name='adresses')
    # ### end Alembic commands ###
